---
pipeline:
  test:
    image: quay.io/digitalpatterns/jdk:11
    environment:
      - GRADLE_USER_HOME=.gradle
    commands:
      - ./gradlew test assemble
    when:
      event:
        - push
        - tag

  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.1
    failure: ignore
    when:
      status:
        - failure
        - success
      event:
        - push
        - pull_request
        - tag

  build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_name
    commands:
      - docker build -t $${DOCKER_NAME} .
    when:
      event:
        - push
        - pull_request
        - tag

  push_to_quay:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_username
      - docker_password
      - docker_server
      - docker_group
      - docker_name
    commands:
      - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} $${DOCKER_SERVER}
      - docker tag $${DOCKER_NAME} $${DOCKER_SERVER}/$${DOCKER_GROUP}/$${DOCKER_NAME}:latest
      - docker push $${DOCKER_SERVER}/$${DOCKER_GROUP}/$${DOCKER_NAME}:latest
    when:
      event: push

  tag_push_to_quay:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_username
      - docker_password
      - docker_server
      - docker_group
      - docker_name
    commands:
      - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} $${DOCKER_SERVER}
      - docker tag $${DOCKER_NAME} $${DOCKER_SERVER}/$${DOCKER_GROUP}/$${DOCKER_NAME}:latest
      - docker push $${DOCKER_SERVER}/$${DOCKER_GROUP}/$${DOCKER_NAME}:latest
    when:
      event: tag
